# Example Site settings

google_analytics: UA-NNNNNNNN-N

header_pages:
  - index.md
  - about.md

footer: 'follow me on <a href="https://github.com/Kyung-Douhyun/">Github</a>'

#style: light # dark (default) or light
#listen_for_clients_preferred_style: true # true or false (default)

plugins:
  - jekyll-seo-tag
baseurl: ''
url: 'https://EC532.github.io'
title: 'EC532'
description: 'EC532 Github.io'
markdown: kramdown
# remote_theme: b2a3e8/jekyll-theme-console
