title: 'EC532'
description: 'EC532 Github.io'
url: 'https://EC532.github.io/'
baseurl: ''

header_pages:
  - index.md
  - about.md

footer: 'follow me on <a href="https://github.com/Kyung-Douhyun/">Github</a>'

style: dark

markdown: kramdown

remote_theme: b2a3e8/jekyll-theme-console
